### PR TITLE
Repository Cleanup

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Update Description**

  `PAYDAY2 mod adding overhauled AI, enemies, tactics and player balancing.`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>

<br>
<br>

## ![Badge Changes]

- Sorted source code into `Source` folder

- Corrected license filename

- Added README stump

- Fixed json syntax of `mod.txt`

- Added license / version badges

  *Version badge is dynamic and bound to `mod.txt`,*
  *however since in your branch the sytanx of `mod.txt`*
  *is broken the badge doesn't work.*

  *With my PR ( and the `mod.txt` fix ) it would look like this:*

  https://github.com/ElectronicsArchiver/Eclipse-Difficulty/commit/be6aa15f37fac716902b5d5aee8cac3180a27b06?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Eclipse-Difficulty

### CODE REVIEW

**Comment by mrcreepysos** [comment]
sorry but i'm not looking for any publicity with this mod, at the moment at least
though i appreciate the effort you put into this and i gotta say thanks for noticing a mistake i left in mod.txt

**Comment by ElectronicsArchiver** [comment]
Well this isn't about publicity, mostly about
making the project more approachable~

**Comment by mrcreepysos** [comment]
some of the edits wouldn't really work with the pd2 blt modding / autoupdating

**Comment by ElectronicsArchiver** [comment]
> some of the edits
Having a source folder?

**Comment by rockymoto517** [comment]
You'll need to update the main.lua as it relies on the current file structure to hook mods

**Comment by rockymoto517** [comment]
You'll likely need to change the download url in the meta.json to accommodate the changes

**Comment by ElectronicsArchiver** [comment]
Thanks, did so, not that it shows up here when it's been closed~

**Comment by mrcreepysos** [comment]
also an issue will rise up when installing the mod since it will require to put that specific source folder into the mods directory of PD2

**Comment by ElectronicsArchiver** [comment]
Even though the download link now points to the source folder?

**Comment by mrcreepysos** [comment]
yea blt just kinda won't recognize that probably

**Pull request closed without merging**
